/*
* generated by Xtext
*/
package tudor.lu.modeling.transformation.ui.contentassist;

import tudor.lu.modeling.transformation.ui.contentassist.AbstractTauHCIProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class TauHCIProposalProvider extends AbstractTauHCIProposalProvider {

}
