/*
* generated by Xtext
*/
package tudor.lu.modeling.transformation;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class TauHCIUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return tudor.lu.modeling.transformation.ui.internal.TauHCIActivator.getInstance().getInjector("tudor.lu.modeling.transformation.TauHCI");
	}
	
}
