/*
 * generated by Xtext
 */
package tudor.lu.modeling.transformation.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TauHCIUiModule extends tudor.lu.modeling.transformation.ui.AbstractTauHCIUiModule {
	public TauHCIUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
