/*
 * generated by Xtext
 */
package tudor.lu.modeling.transformation;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TauHCIRuntimeModule extends tudor.lu.modeling.transformation.AbstractTauHCIRuntimeModule {

}
