/*
* generated by Xtext
*/
package tudor.lu.modeling.transformation.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class TauHCIOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
