/*
* generated by Xtext
*/
package tudor.lu.modeling.transformation.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import tudor.lu.modeling.transformation.services.TauHCIGrammarAccess;

public class TauHCIParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TauHCIGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected tudor.lu.modeling.transformation.parser.antlr.internal.InternalTauHCIParser createParser(XtextTokenStream stream) {
		return new tudor.lu.modeling.transformation.parser.antlr.internal.InternalTauHCIParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public TauHCIGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TauHCIGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
