/*
* generated by Xtext
*/
package tudor.lu.modeling.transformation.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TauHCIAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("tudor/lu/modeling/transformation/parser/antlr/internal/InternalTauHCI.tokens");
	}
}
