/*
 * generated by Xtext
 */
package tudor.lu.modeling.transformation.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TauHCIExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return tudor.lu.modeling.transformation.ui.internal.TauHCIActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return tudor.lu.modeling.transformation.ui.internal.TauHCIActivator.getInstance().getInjector("tudor.lu.modeling.transformation.TauHCI");
	}
	
}
